# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=255)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='next_api.Conversation')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('hometown', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('facebook_profile', models.URLField()),
                ('picture', models.ImageField(upload_to=b'')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='next_api.Person'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='next_api.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set([('person1', 'person2')]),
        ),
    ]
